# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spaghetti-san Blog
email: spaghettisan@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  All about anything from Spaghetti-san
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spaghetti-san.github.io" # the base hostname & protocol for your site
twitter_username: axlyody
github_username:  spaghetti-san
facebook_username:  profile.php?id=100007594726461

# Gems
gems: [jekyll-paginate]

# Conig
paginate: 3
paginate_path: "page/:num"
# Build settings
markdown: kramdown
